server.port=8080
spring.application.name=API-GATEWAY

# Eureka Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Route 0: Auth
spring.cloud.gateway.server.webflux.routes[0].id=USER-SERVICE-AUTH
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# Route 1: Users
spring.cloud.gateway.server.webflux.routes[1].id=USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/**

# Route 2: Exams
spring.cloud.gateway.server.webflux.routes[2].id=EXAM-SERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=lb://EXAM-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/exams/**

# Route 3: Results
spring.cloud.gateway.server.webflux.routes[3].id=RESULT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].uri=lb://RESULT-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/results/**
